version: "3.9"
services:
  rembg_api:
    build: ./rembg_api
    ports:
      - "8000:80"
    hostname: rembgapi
  classifier_api:
    build: ./classifier_api
    ports:
      - "8001:80"
    hostname: classifier_api
  color_api:
    build: ./color_api
    ports:
      - "8002:80"
    hostname: color_api
  vong_api:
    build: ./vong_api
    ports:
      - "8003:80"
    hostname: vong_api